# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_bak.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1232, 791)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.FileList = QtWidgets.QTextBrowser(self.centralwidget)
        self.FileList.setObjectName("FileList")
        self.verticalLayout.addWidget(self.FileList)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.ResultTable = QtWidgets.QTableWidget(self.centralwidget)
        self.ResultTable.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.ResultTable.setFont(font)
        self.ResultTable.setAutoFillBackground(True)
        self.ResultTable.setStyleSheet("QHeaderView::section\n"
"{\n"
"spacing: 10px;\n"
"background-color:lightgray;\n"
"color: black;\n"
"margin: 0px;\n"
"text-align: center;\n"
"};\n"
"\n"
"QTableView::item::section\n"
"{\n"
"spacing: 10px;\n"
"background-color:lightblue;\n"
"color: black;\n"
"border: 1px solid black;\n"
"margin: 0px;\n"
"text-align: center;\n"
"}")
        self.ResultTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ResultTable.setShowGrid(True)
        self.ResultTable.setGridStyle(QtCore.Qt.SolidLine)
        self.ResultTable.setObjectName("ResultTable")
        self.ResultTable.setColumnCount(4)
        self.ResultTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.ResultTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(173, 173, 173))
        self.ResultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ResultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ResultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ResultTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setItem(0, 3, item)
        self.ResultTable.horizontalHeader().setCascadingSectionResizes(False)
        self.ResultTable.horizontalHeader().setDefaultSectionSize(100)
        self.ResultTable.horizontalHeader().setSortIndicatorShown(False)
        self.ResultTable.horizontalHeader().setStretchLastSection(True)
        self.ResultTable.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        self.ResultTable.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.ResultTable.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.ResultTable.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)
        self.ResultTable.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.ResultTable)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 30))
        self.menubar.setObjectName("menubar")
        self.FileMenu = QtWidgets.QMenu(self.menubar)
        self.FileMenu.setObjectName("FileMenu")
        self.ConfigMenu = QtWidgets.QMenu(self.menubar)
        self.ConfigMenu.setObjectName("ConfigMenu")
        self.ProcessMenu = QtWidgets.QMenu(self.menubar)
        self.ProcessMenu.setObjectName("ProcessMenu")
        self.CleanMenu = QtWidgets.QMenu(self.menubar)
        self.CleanMenu.setObjectName("CleanMenu")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)
        self.B0Set = QtWidgets.QAction(Form)
        self.B0Set.setObjectName("B0Set")
        self.ChooseDir = QtWidgets.QAction(Form)
        self.ChooseDir.setObjectName("ChooseDir")
        self.ChooseFile = QtWidgets.QAction(Form)
        self.ChooseFile.setObjectName("ChooseFile")
        self.CurveFiles = QtWidgets.QAction(Form)
        self.CurveFiles.setObjectName("CurveFiles")
        self.FeatureValue = QtWidgets.QAction(Form)
        self.FeatureValue.setObjectName("FeatureValue")
        self.actionCleanResult = QtWidgets.QAction(Form)
        self.actionCleanResult.setObjectName("actionCleanResult")
        self.actionCleanFile = QtWidgets.QAction(Form)
        self.actionCleanFile.setObjectName("actionCleanFile")
        self.FileMenu.addAction(self.ChooseDir)
        self.FileMenu.addAction(self.ChooseFile)
        self.ConfigMenu.addAction(self.B0Set)
        self.ProcessMenu.addAction(self.CurveFiles)
        self.ProcessMenu.addAction(self.FeatureValue)
        self.CleanMenu.addAction(self.actionCleanResult)
        self.CleanMenu.addAction(self.actionCleanFile)
        self.menubar.addAction(self.FileMenu.menuAction())
        self.menubar.addAction(self.ConfigMenu.menuAction())
        self.menubar.addAction(self.ProcessMenu.menuAction())
        self.menubar.addAction(self.CleanMenu.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.label.setText(_translate("Form", "文件列表"))
        self.label_2.setText(_translate("Form", "处理结果"))
        self.ResultTable.setSortingEnabled(False)
        item = self.ResultTable.verticalHeaderItem(0)
        item.setText(_translate("Form", "20170502-28-R.txt"))
        item = self.ResultTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "L0"))
        item = self.ResultTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Lm"))
        item = self.ResultTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Bm"))
        item = self.ResultTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Lm/L0"))
        __sortingEnabled = self.ResultTable.isSortingEnabled()
        self.ResultTable.setSortingEnabled(False)
        item = self.ResultTable.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.ResultTable.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.ResultTable.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.ResultTable.item(0, 3)
        item.setText(_translate("Form", "0"))
        self.ResultTable.setSortingEnabled(__sortingEnabled)
        self.FileMenu.setTitle(_translate("Form", "文件导入"))
        self.ConfigMenu.setTitle(_translate("Form", "参数配置"))
        self.ProcessMenu.setTitle(_translate("Form", "数据处理"))
        self.CleanMenu.setTitle(_translate("Form", "数据清理"))
        self.menu.setTitle(_translate("Form", "帮助"))
        self.B0Set.setText(_translate("Form", "B0范围"))
        self.ChooseDir.setText(_translate("Form", "选择目录"))
        self.ChooseFile.setText(_translate("Form", "选择文件"))
        self.CurveFiles.setText(_translate("Form", "特征曲线"))
        self.FeatureValue.setText(_translate("Form", "特征值"))
        self.actionCleanResult.setText(_translate("Form", "CleanResult"))
        self.actionCleanFile.setText(_translate("Form", "CleanFile"))

